# Generated by Django 6.0.4 on 2026-04-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_address_order_name_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
